### ISSUE TITLE
Some cleaning tasks

### ISSUE THREAD

**Issue by sbacchio** [Lyncs-API/lyncs.quda#10]
@sy3394 here a list of some tasks for the cleaning branch:
- [X] run `lyncs_pylint` and try to solve most comments as possible (addressed by #15)
- [X] fix the pylint workflow that currently is failing (see lyncs_utils for reference) (addressed by #15)
- [x] fix also the budges in the README
- [X] would be nice to use `enums.py` more systematically in the package (I believe I used it in few places) (addressed by #14)
- [X] write a patch for using `std::exception` in `errorQuda` (addressed by #15)
- [X] subclassing ndarray (addressed by #12)
